# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-18 01:44
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(default='', max_length=250)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image', models.URLField(default='')),
                ('game', models.URLField(default='')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.10'), max_digits=4)),
                ('timesplayed', models.IntegerField(default=0)),
                ('timesbought', models.IntegerField(default=0)),
                ('highscores', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('bought', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('genre', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25), max_length=10, size=None)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
